#!/bin/bash
#SBATCH -p 256GB
#SBATCH -n 48
# #SBATCH --gres=gpu:1
#SBATCH --mem=192g
#SBATCH -t 28-00:00:00
#SBATCH -o all_job.log
#SBATCH -e all_job.err
#SBATCH -J all_job


# job goes like python step18_bootstrap_new.py GDT_TS
# all measures are: ['GDT_TS', 'GDT_HA', 'GDC_SC', 'GDC_ALL', 'RMS_CA', 'RMS_ALL', 'AL0_P','AL4_P', 'ALI_P', 'LGA_S', 'RMSD[L]', 'MolPrb_Score', 'LDDT','CAD_AA', 'RPF', 'TMscore', 'FlexE', 'QSE', 'CAD_SS', 'MP_clash','CAD_AA', 'RPF', 'TMscore', 'FlexE', 'QSE', 'CAD_SS', 'MP_clash',            'MP_rotout', 'MP_ramout', 'MP_ramfv', 'reLLG_lddt', 'reLLG_const']
# measures = (GDT_TS, GDT_HA, GDC_SC, 'GDC_ALL', 'RMS_CA', 'RMS_ALL', 'AL0_P','AL4_P', 'ALI_P', 'LGA_S', 'RMSD[L]', 'MolPrb_Score', 'LDDT','CAD_AA', 'RPF', 'TMscore', 'FlexE', 'QSE', 'CAD_SS', 'MP_clash','CAD_AA', 'RPF', 'TMscore', 'FlexE', 'QSE', 'CAD_SS', 'MP_clash', 'MP_rotout', 'MP_ramout', 'MP_ramfv', 'reLLG_lddt', 'reLLG_const')

# define a variable for the model
MODEL=best
# define a variable for the impute value
IMPUTE_VALUE=-2

echo "starting step11_process_new_EU_score.py"
python step11_process_new_EU_score.py --model $MODEL --impute_value $IMPUTE_VALUE &
wait
echo "starting step20_process_new_interface_score.py"
python step20_process_new_interface_score.py --model $MODEL --impute_value $IMPUTE_VALUE &
wait
echo "starting step21_bootstrap_sum_new_interface.py"
python step21_bootstrap_sum_new_interface.py --model $MODEL --impute_value $IMPUTE_VALUE &
wait