#!/bin/bash
#SBATCH -p 256GB
#SBATCH -n 48
#SBATCH --mem=192g
#SBATCH -t 28-00:00:00
#SBATCH -o all_job_np.log
#SBATCH -e all_job_np.err
#SBATCH -J all_job_np

# 参数组合
MODELS=("best" "first")
IMPUTE_VALUES=(0 -2)
STAGE=1
MODE=all

for MODEL in "${MODELS[@]}"; do
    for IMPUTE_VALUE in "${IMPUTE_VALUES[@]}"; do

        echo "Starting tasks for MODEL=$MODEL, IMPUTE_VALUE=$IMPUTE_VALUE"
        
        echo "starting step11_process_new_EU_score.py"
        python step11_process_new_EU_score.py --model $MODEL --impute_value $IMPUTE_VALUE --out_dir ./score_EU_v2_np/ --stage $STAGE --bad_targets T1219 T1246 T1249 T1269 T1295 &
        wait

        echo "starting step20_process_new_interface_score.py"
        python step20_process_new_interface_score.py --model $MODEL --impute_value $IMPUTE_VALUE --out_dir ./score_interface_v2_np/ --stage $STAGE --bad_targets T1219 T1246 T1249 T1269 T1295 &
        wait

        echo "starting step17_process_T1249o_EU_score.py"
        python step17_process_T1249o_EU_score.py --model $MODEL --impute_value $IMPUTE_VALUE --out_dir ./score_EU_v2_np/ --stage $STAGE &
        wait

        echo "starting step18_process_T1249o_interface_score.py"
        python step18_process_T1249o_interface_score.py --model $MODEL --impute_value $IMPUTE_VALUE --out_dir ./score_interface_v2_np/ --stage $STAGE &
        wait

        echo "starting step21_bootstrap_sum_new_interface.py"
        python step21_bootstrap_sum_new_interface.py --model $MODEL --impute_value $IMPUTE_VALUE --interface_score_path ./score_interface_v2_np/ --EU_score_path ./score_EU_v2_np/ --output_path ./out_v2_np/ &
        wait

        echo "starting step23_heatmap.py"
        python step23_heatmap.py --model $MODEL --impute_value $IMPUTE_VALUE --interface_score_path ./score_interface_v2_np/ --EU_score_path ./score_EU_v2_np/ --output_path ./out_v2_np/ &
        wait

    done
done
