#!/bin/bash
#SBATCH -p 256GB
#SBATCH -n 48
#SBATCH --mem=192g
#SBATCH -t 28-00:00:00
#SBATCH -o model_6.log
#SBATCH -e model_6.err
#SBATCH -J model_6


# job goes like python step18_bootstrap_new.py GDT_TS
# all measures are: ['GDT_TS', 'GDT_HA', 'GDC_SC', 'GDC_ALL', 'RMS_CA', 'RMS_ALL', 'AL0_P','AL4_P', 'ALI_P', 'LGA_S', 'RMSD[L]', 'MolPrb_Score', 'LDDT','CAD_AA', 'RPF', 'TMscore', 'FlexE', 'QSE', 'CAD_SS', 'MP_clash','CAD_AA', 'RPF', 'TMscore', 'FlexE', 'QSE', 'CAD_SS', 'MP_clash',            'MP_rotout', 'MP_ramout', 'MP_ramfv', 'reLLG_lddt', 'reLLG_const']
# measures = (GDT_TS, GDT_HA, GDC_SC, 'GDC_ALL', 'RMS_CA', 'RMS_ALL', 'AL0_P','AL4_P', 'ALI_P', 'LGA_S', 'RMSD[L]', 'MolPrb_Score', 'LDDT','CAD_AA', 'RPF', 'TMscore', 'FlexE', 'QSE', 'CAD_SS', 'MP_clash','CAD_AA', 'RPF', 'TMscore', 'FlexE', 'QSE', 'CAD_SS', 'MP_clash', 'MP_rotout', 'MP_ramout', 'MP_ramfv', 'reLLG_lddt', 'reLLG_const')

# define a variable for the model
MODEL1=first
MODEL6=sixth
# define a variable for the impute value
IMPUTE_VALUE=-2
MODE=all

echo "starting step11_process_new_EU_score.py"
python step11_process_new_EU_score.py --model $MODEL1 --impute_value $IMPUTE_VALUE &
wait

echo "starting step11_process_new_EU_score.py"
python step11_process_new_EU_score.py --model $MODEL6 --impute_value $IMPUTE_VALUE &
wait
# echo "starting step20_process_new_interface_score.py"
# python step20_process_new_interface_score.py --model $MODEL --impute_value $IMPUTE_VALUE &
# wait

# echo "starting step21_bootstrap_sum_new_interface.py"
# python step21_bootstrap_sum_new_interface.py --model $MODEL --impute_value $IMPUTE_VALUE --output_path ./bootstrap_new_interface/ &
# wait

# echo "starting step23_heatmap.py"
# python step23_heatmap.py --model $MODEL --impute_value $IMPUTE_VALUE --output_path ./heatmap_interface/ &
# wait