#!/bin/bash
#SBATCH -p 256GB
#SBATCH -n 48
#SBATCH --mem=192g
#SBATCH -t 28-00:00:00
#SBATCH -o T2_job.log
#SBATCH -e T2_job.err
#SBATCH -J T2_job

# 定义参数列表
MODELS=("best" "first")
IMPUTE_VALUES=(0 -2)
STAGE=2

for MODEL in "${MODELS[@]}"; do
    for IMPUTE_VALUE in "${IMPUTE_VALUES[@]}"; do
        echo "Running with MODEL=$MODEL, IMPUTE_VALUE=$IMPUTE_VALUE"

        echo "starting step11_process_new_EU_score.py"
        python step11_process_new_EU_score.py --model $MODEL --impute_value $IMPUTE_VALUE --out_dir ./score_EU_v2_T2/ --stage $STAGE --bad_targets  T2246   &
        wait

        echo "starting step20_process_new_interface_score.py"
        python step20_process_new_interface_score.py --model $MODEL --impute_value $IMPUTE_VALUE --out_dir ./score_interface_v2_T2/ --stage $STAGE --bad_targets  T2246   &
        wait

        # 如果需要恢复 step17 和 step18，可以取消注释
        # echo "starting step17_process_T1249o_EU_score.py"
        # python step17_process_T1249o_EU_score.py --model $MODEL --impute_value $IMPUTE_VALUE --out_dir ./score_EU_v2_T2/ --stage $STAGE &
        # wait

        # echo "starting step18_process_T1249o_interface_score.py"
        # python step18_process_T1249o_interface_score.py --model $MODEL --impute_value $IMPUTE_VALUE --out_dir ./score_interface_v2_T2/ --stage $STAGE &
        # wait

        echo "starting step21_bootstrap_sum_new_interface.py"
        python step21_bootstrap_sum_new_interface.py --model $MODEL --impute_value $IMPUTE_VALUE --interface_score_path ./score_interface_v2_T2/ --EU_score_path ./score_EU_v2_T2/ --output_path ./out_v2_T2/ &
        wait

        echo "starting step23_heatmap.py"
        python step23_heatmap.py --model $MODEL --impute_value $IMPUTE_VALUE --interface_score_path ./score_interface_v2_T2/ --EU_score_path ./score_EU_v2_T2/ --output_path ./out_v2_T2/ &
        wait

    done
done
