#!/bin/bash
#SBATCH -p 256GB
#SBATCH -n 48
#SBATCH --mem=192g
#SBATCH -t 28-00:00:00
#SBATCH -o all_job.log
#SBATCH -e all_job.err
#SBATCH -J all_job


MODEL=best
IMPUTE_VALUE=-2
MODE=all


echo "starting step10_sum_z-score.py"
python -u step10_sum_z-score.py --model $MODEL --impute_value $IMPUTE_VALUE --mode $MODE &
wait
echo "starting step28_bootstrap_sum.py"
python -u step28_bootstrap_sum.py --model $MODEL --impute_value $IMPUTE_VALUE --mode $MODE &
wait

# echo "starting step30_bootstrap_t-test.py"
# python -u step30_bootstrap_t-test.py --bootstrap_rounds 100 --model best --equal_weight --impute_value -2 &
# wait