#!/bin/bash
#SBATCH -p 256GB
#SBATCH -n 48
#SBATCH --mem=192g
#SBATCH -t 28-00:00:00
#SBATCH -o CASP15_job.log
#SBATCH -e CASP15_job.err
#SBATCH -J CASP15_job


MODEL=best
IMPUTE_VALUE=-2
MODE=all
CSV_PATH=./monomer_CASP15_data/
CSV_PATH_RAW=./monomer_CASP15_data/raw_data/

rm -r $CSV_PATH
echo "starting step0_data_process_EU.py"
python -u step0_data_process_EU.py --input_path /home2/s439906/data/CASP16/regular/ --output_path $CSV_PATH &
wait

echo "starting step10_sum_z-score.py"
python -u step10_sum_z-score.py --csv_path $CSV_PATH_RAW --out_path ./group_by_target_CASP15/ --model $MODEL --impute_value $IMPUTE_VALUE --mode $MODE &
wait