#!/bin/bash
#SBATCH -p 256GB
#SBATCH -n 48
#SBATCH --mem=192g
#SBATCH -t 28-00:00:00
#SBATCH -o CASP15_job.log
#SBATCH -e CASP15_job.err
#SBATCH -J CASP15_job


MODEL=best
IMPUTE_VALUE=-2
MODE=all
SCORE_PATH=./monomer_data_CASP15/
SCORE_PATH_RAW=./monomer_data_CASP15/raw_data/
STAGE=1

rm -r $SCORE_PATH
echo "starting data_process.py"
python -u data_process.py --input_path /home2/s439906/data/CASP16/regular/ --output_path $SCORE_PATH &
wait

# echo "starting step10_sum_z-score.py"
# python -u step10_sum_z-score.py --csv_path $CSV_PATH_RAW --out_path ./group_by_target_CASP15/ --model $MODEL --impute_value $IMPUTE_VALUE --mode $MODE &
# wait

echo  "starting get_raw_score.py"
python -u get_raw_score.py --model $MODEL --impute_value $IMPUTE_VALUE --mode $MODE --phase $STAGE --csv_path $SCORE_PATH_RAW  --out_path ./score_CASP15/ &
wait