#!/bin/bash
#SBATCH -p 256GB
#SBATCH -n 48
#SBATCH --mem=192g
#SBATCH -t 28-00:00:00
#SBATCH -o t-test_job.log
#SBATCH -e t-test_job.err
#SBATCH -J t-test_job


# job goes like python step18_bootstrap_new.py GDT_TS
# all measures are: ['GDT_TS', 'GDT_HA', 'GDC_SC', 'GDC_ALL', 'RMS_CA', 'RMS_ALL', 'AL0_P','AL4_P', 'ALI_P', 'LGA_S', 'RMSD[L]', 'MolPrb_Score', 'LDDT','CAD_AA', 'RPF', 'TMscore', 'FlexE', 'QSE', 'CAD_SS', 'MP_clash','CAD_AA', 'RPF', 'TMscore', 'FlexE', 'QSE', 'CAD_SS', 'MP_clash',            'MP_rotout', 'MP_ramout', 'MP_ramfv', 'reLLG_lddt', 'reLLG_const']
# measures = (GDT_TS, GDT_HA, GDC_SC, 'GDC_ALL', 'RMS_CA', 'RMS_ALL', 'AL0_P','AL4_P', 'ALI_P', 'LGA_S', 'RMSD[L]', 'MolPrb_Score', 'LDDT','CAD_AA', 'RPF', 'TMscore', 'FlexE', 'QSE', 'CAD_SS', 'MP_clash','CAD_AA', 'RPF', 'TMscore', 'FlexE', 'QSE', 'CAD_SS', 'MP_clash', 'MP_rotout', 'MP_ramout', 'MP_ramfv', 'reLLG_lddt', 'reLLG_const')

MODEL=best
IMPUTE_VALUE=-2
MODE=all

echo "starting step10_sum_z-score.py"
python -u step10_sum_z-score.py --model $MODEL --impute_value $IMPUTE_VALUE --mode $MODE &
wait
# echo "starting step28_bootstrap_sum.py"
# python -u step28_bootstrap_sum.py --model $MODEL --impute_value $IMPUTE_VALUE --mode $MODE &
# wait
echo "starting step30_bootstrap_t-test.py"
python -u step30_bootstrap_t-test.py --bootstrap_rounds 10 --model $MODEL --impute_value $IMPUTE_VALUE  --mode $MODE &
wait