#!/bin/bash
#SBATCH -p 256GB
#SBATCH -n 48
#SBATCH --mem=192g
#SBATCH -t 28-00:00:00
#SBATCH -o T0_job.log
#SBATCH -e T0_job.err
#SBATCH -J T0_job



MODEL=first
IMPUTE_VALUE=-2
MODE=all
SCORE_PATH=./monomer_data_T0_EU/
SCORE_PATH_RAW=./monomer_data_T0_EU/raw_data/
SCORE_PATH_PROCESSED=./monomer_data_T0_EU/processed/
STAGE=0

rm -r $SCORE_PATH

echo "starting data_process_EU.py"
python -u data_process.py --output_path $SCORE_PATH --phase $STAGE
echo  "starting get_raw_score.py"
python -u get_raw_score.py --model $MODEL --impute_value $IMPUTE_VALUE --mode $MODE --phase $STAGE --csv_path $SCORE_PATH_RAW  --out_path ./score_T0/