#!/bin/bash
#SBATCH -p 256GB
#SBATCH -n 48
#SBATCH --mem=192g
#SBATCH -t 28-00:00:00
#SBATCH -o T2_job.log
#SBATCH -e T2_job.err
#SBATCH -J T2_job


MODEL=best
IMPUTE_VALUE=-2
MODE=all

# remove ./monomer_data_T2_EU/ path
rm -r ./monomer_data_T2_EU/

echo "starting step0_data_process_EU.py"
python -u step0_data_process_EU.py --stage 2
wait

echo "starting step10_sum_z-score.py"
python -u step10_sum_z-score.py --model $MODEL --impute_value $IMPUTE_VALUE --mode $MODE --csv_path ./monomer_data_T2_EU/raw_data/  --out_path ./score_T2/ &
wait

echo "starting step28_bootstrap_sum.py"
python -u step28_bootstrap_sum.py --model $MODEL --impute_value $IMPUTE_VALUE --mode $MODE --score_path ./score_T2/ --output_path ./out_T2/ &
wait

echo "starting step32_heatmap.py"
python -u step32_heatmap.py --model $MODEL --impute_value $IMPUTE_VALUE --mode $MODE --score_path ./score_T2/ --output_path ./out_T2/ &
wait
