#!/bin/bash
#SBATCH -p 256GB
#SBATCH -n 48
#SBATCH --mem=192g
#SBATCH -t 28-00:00:00
#SBATCH -o T2_job.log
#SBATCH -e T2_job.err
#SBATCH -J T2_job


MODEL=best
IMPUTE_VALUE=-2
MODE=all
SCORE_PATH=./monomer_data_T2_EU/
SCORE_PATH_RAW=./monomer_data_T2_EU/raw_data/
SCORE_PATH_PROCESSED=./monomer_data_T2_EU/processed/
STAGE=2
# remove ./monomer_data_T2_EU/ path
rm -r $SCORE_PATH

echo "starting data_process.py"
python -u data_process.py --output_path $SCORE_PATH --phase $STAGE
echo  "starting get_raw_score.py"
python -u get_raw_score.py --model $MODEL --impute_value $IMPUTE_VALUE --mode $MODE --phase $STAGE --csv_path $SCORE_PATH_RAW  --out_path ./score_T2/